CREATE TABLE Orders (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderTime DATETIME NOT NULL,
    CashierID INTEGER,
    OrderTypeID INTEGER,
    PaymentTypeID INTEGER,
    FOREIGN KEY (CashierID) REFERENCES Cashiers(CashierID)
);

CREATE TABLE Cashiers (
    CashierID INTEGER PRIMARY KEY AUTOINCREMENT,
    CashierName VARCHAR(30),
    CashierSurname VARCHAR(30)
);

CREATE TABLE OrderTypes (
    OrderTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderType VARCHAR(50)
);