CREATE TABLE Orders (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderTime DATETIME NOT NULL,
    CashierID INTEGER,
    OrderTypeID INTEGER,
    PaymentTypeID INTEGER
);

CREATE TABLE Cashiers (
    CashierID INTEGER PRIMARY KEY AUTOINCREMENT,
    CashierName VARCHAR(30),
    CashierSurname VARCHAR(30)
);